
FORMAT: 1A
HOST: https://alefba.roshan-ai.ir

# الفبا

<div dir=rtl>
نویسه‌خوان الفبا تصویر اسناد فارسی، انگلیسی و عربی را می‌خواند و در قالب متن مرتب ارائه می‌دهد.
</div>

<blockquote dir=rtl>
برای دسترسی به واسط برنامه‌نویس الفبا نیاز به یک TOKEN_KEY معتبر دارید که برای احراز هویت استفاده می‌شود. لطفا برای آزمایش سامانه، این متغیر را در تقاضاهای نمونه، جای‌گذاری کنید. سوال هم اگر دارید، لطفا برای آدرس alefba@roshan-ai.ir بنویسید.
</blockquote>


## خواندن سند [/api/read_document/]

<div dir=rtl>
این تابع، یک سند را دریافت می‌کند و متن صفحات آن را در قالب JSON باز می‌گرداند. خروجی نویسه‌خوان شامل بخش‌های نوشته (پاراگراف)، جدول و تصویر است. مکان و ابعاد هر بخش در خروجی مشخص شده است و اطلاعات کامل خطوط متن در بخش نوشته ظاهر می‌شود. برای هر خط متن، ویژگی احتمال صحت هم قرار داده شده که نشان می‌دهد ابزار نویسه‌خوان چقدر از نتیجه تحلیل، مطمئن است.
</div>

### نمونه [POST]

<div dir=rtl>
می‌توانید برای همین تابع، فایل سند را به طور مستقیم و در قالب تقاضای <code>multipart/form-data</code> ارسال نمایید:
</div>

> curl -X POST --header "Authorization: Token TOKEN_KEY" -F "document=@example.pdf" http://alefba.roshan-ai.ir/api/read_document

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Attributes

        - document_url: URL (string, required) - آدرس سند ورودی
        - type: general (enum[string]) - این ویژگی نوع سند را مشخص می‌کند
            + Members
                + `general` - سندهای عمومی
                + `ID-card` - کارت‌های شناسایی
                + `excel` - جدولهای مالی
        - fix_orientation: true (boolean) - در صورت فعال بودن این ویژگی، الفبا سعی می‌کند چرخش ۹۰، ۱۸۰ و یا ۲۷۰ درجه تصویر را اصلاح کند
        - word_positions: true (boolean) - در صورت فعال بودن این ویژگی اطلاعات مکانی واژه‌ها در خروجی قرار می‌گیرد
        - wait: true (boolean) - اگر این ویژگی فعال باشد، کاربر منتظر می‌ماند تا نتیجه تحلیل آماده شود؛ در غیر این صورت، تقاضای تحلیل دریافت می‌شود و کاربر با استفاده از واسط «وضعیت سند» از میزان پیشرفت تحلیل مطلع می‌شود. به این ترتیب پس از پایان پردازش، تقاضای جدیدی برای پردازش سند ارسال می‌شود و این بار تقاضا با نتیجه مناسب پاسخ داده می‌شود.

    + Body

            {
              "document_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf",
              "fix_orientation": true,
              "word_positions": false,
              "type": "general",
              "wait": true
            }

+ Response 200 (application/json)

        {
          "document_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf",
          "pages": [{
            "page_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf@page=1",
            "width": 2125,
            "height": 2750,
            "text": "بوته\n\nدرس‌های دانشگاهی معمولا با پروژه‌هابی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها\n...",
            "parts": [
              {
                "type": "text",
                "direction": "rtl",
                "box": "209 305 1711 449",
                "text": "درس‌های دانشگاهی معمولا با پروژه‌هابی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها\n...",
                "lines": [
                  {
                    "probability": 1.0,
                    "box": "211 305 1707 57",
                    "text": "درس‌های دانشگاهی معمولا با پروژه‌هایی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها"
                  },
                  ...
                ]
              },
              ...
            ]
          },{
            "page_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf@page=2",
            "width": 2125,
            "height": 2750,
            "text": "انجام این کار البته چندان هم آسان نیست؛ نه برای دانشجوها و نه برای کمک‌استادها، اما حاصل بسیار شیرین\n...",
            "parts": [
              {
                "type": "text",
                "direction": "rtl",
                "box": "210 110 1714 294",
                "text": "انجام این کار البته چندان هم آسان نیست؛ نه برای دانشجوها و نه برای کمک‌استادها، اما حاصل بسیار شیرین\n...",
                "lines": [
                  {
                    "probability": 1.0,
                    "box": "210 110 1706 58",
                    "text": "انجام این کار البته چندان هم آسان نیست؛ نه برای دانشجوها و نه برای کمک‌استادها، اما حاصل بسیار شیرین"
                  },
                  ...
                ],
              },
              ...
            ]
          }]
        }


## خواندن صفحه [/api/read_pages/]

<div dir=rtl>
این تابع، تصویر نوشته را دریافت می‌کند و متن آن را در قالب JSON باز می‌گرداند. خروجی نویسه‌خوان شامل بخش‌های نوشته (پاراگراف)، جدول و تصویر است. مکان و ابعاد هر بخش در خروجی مشخص شده است و اطلاعات کامل خطوط متن در بخش نوشته ظاهر می‌شود. برای هر خط متن، ویژگی احتمال صحت هم قرار داده شده که نشان می‌دهد ابزار نویسه‌خوان چقدر از نتیجه تحلیل، مطمئن است.
</div>




<div dir=rtl>
می‌توانید برای همین تابع، فایل سند را به طور مستقیم و در قالب تقاضای <code>multipart/form-data</code> ارسال نمایید:
</div>

> curl -X POST --header "Authorization: Token TOKEN_KEY" -F "document=@example.pdf" http://alefba.roshan-ai.ir/api/read_document

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY
            Content-Type:multipart/form-data; boundary={boundary value}

    + Attributes

        - document: (string, required) - فایل سند ورودی
        - type: general (enum[string]) - این ویژگی نوع سند را مشخص می‌کند
            + Members
                + `general` - سندهای عمومی
                + `ID-card` - کارت‌های شناسایی
                + `excel` - جدولهای مالی
        - fix_orientation: true (boolean) - در صورت فعال بودن این ویژگی، الفبا سعی می‌کند چرخش ۹۰، ۱۸۰ و یا ۲۷۰ درجه تصویر را اصلاح کند
        - word_positions: true (boolean) - در صورت فعال بودن این ویژگی اطلاعات مکانی واژه‌ها در خروجی قرار می‌گیرد
        - wait: true (boolean) - اگر این ویژگی فعال باشد، کاربر منتظر می‌ماند تا نتیجه تحلیل آماده شود؛ در غیر این صورت، تقاضای تحلیل دریافت می‌شود و کاربر با استفاده از واسط «وضعیت سند» از میزان پیشرفت تحلیل مطلع می‌شود. به این ترتیب پس از پایان پردازش، تقاضای جدیدی برای پردازش سند ارسال می‌شود و این بار تقاضا با نتیجه مناسب پاسخ داده می‌شود.

    + Body


            --{boundary value}
            Content-Disposition: form-data; name='fix_orientation'

            true

            --{boundary value}
            Content-Disposition: form-data; name='word_positions'

            false

            --{boundary value}
            Content-Disposition: form-data; name='type'

            "general"

            --{boundary value}
            Content-Disposition: form-data; name='wait'

            true

            --{boundary value}
            Content-Disposition: form-data; name='document'; filename='FILE NAME'
            Content-Type: text/plain (according to the type of the uploaded file)

            {file content}
            --{boundary value}


+ Response 200 (application/json)

        {
          "pages": [{
            "page_url": "http://alefba.roshan-ai.ir/media/files/96/84/859267728361-boute.pdf@page=1",
            "width": 2125,
            "height": 2750,
            "text": "بوته\n\nدرس‌های دانشگاهی معمولا با پروژه‌هابی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها\n...",
            "parts": [
              {
                "type": "text",
                "direction": "rtl",
                "box": "209 305 1711 449",
                "text": "درس‌های دانشگاهی معمولا با پروژه‌هابی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها\n...",
                "lines": [
                  {
                    "probability": 1.0,
                    "box": "211 305 1707 57",
                    "text": "درس‌های دانشگاهی معمولا با پروژه‌هایی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها"
                  },
                  ...
                ]
              },
              ...
            ]
          },{
            "page_url":"http://alefba.roshan-ai.ir/media/files/96/84/859267728361-boute.pdf@page=2",
            "width": 2125,
            "height": 2750,
            "text": "انجام این کار البته چندان هم آسان نیست؛ نه برای دانشجوها و نه برای کمک‌استادها، اما حاصل بسیار شیرین\n...",
            "parts": [
              {
                "type": "text",
                "direction": "rtl",
                "box": "210 110 1714 294",
                "text": "انجام این کار البته چندان هم آسان نیست؛ نه برای دانشجوها و نه برای کمک‌استادها، اما حاصل بسیار شیرین\n...",
                "lines": [
                  {
                    "probability": 1.0,
                    "box": "210 110 1706 58",
                    "text": "انجام این کار البته چندان هم آسان نیست؛ نه برای دانشجوها و نه برای کمک‌استادها، اما حاصل بسیار شیرین"
                  },
                  ...
                ],
              },
              ...
            ]
          }],
          "document_url":"http://alefba.roshan-ai.ir/media/files/96/84/859267728361-boute.pdf"
        }


## خواندن صفحه [/api/read_pages/]

<div dir=rtl>
این تابع، تصویر نوشته را دریافت می‌کند و متن آن را در قالب JSON باز می‌گرداند. خروجی نویسه‌خوان شامل بخش‌های نوشته (پاراگراف)، جدول و تصویر است. مکان و ابعاد هر بخش در خروجی مشخص شده است و اطلاعات کامل خطوط متن در بخش نوشته ظاهر می‌شود. برای هر خط متن، ویژگی احتمال صحت هم قرار داده شده که نشان می‌دهد ابزار نویسه‌خوان چقدر از نتیجه تحلیل، مطمئن است.
</div>

### نمونه [POST]

<div dir=rtl>
می‌توانید برای همین تابع، فایل صفحه را به طور مستقیم و در قالب تقاضای <code>multipart/form-data</code> ارسال نمایید:
</div>

> curl -X POST --header "Authorization: Token TOKEN_KEY" -F "page=@example.jpg" http://alefba.roshan-ai.ir/api/read_pages

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Attributes

        - page_urls: URL1, URL2, ... (array[string], required) - آدرس صفحات ورودی
        - type: general (enum[string]) - این ویژگی نوع سند را مشخص می‌کند
            + Members
                + `general` - سندهای عمومی
                + `ID-card` - کارت‌های شناسایی
                + `excel` - جدولهای مالی
        - fix_orientation: true (boolean) - در صورت فعال بودن این ویژگی، الفبا سعی می‌کند چرخش ۹۰، ۱۸۰ و یا ۲۷۰ درجه تصویر را اصلاح کند
        - word_positions: true (boolean) - در صورت فعال بودن این ویژگی اطلاعات مکانی واژه‌ها در خروجی قرار می‌گیرد
        - wait: true (boolean) - اگر این ویژگی فعال باشد، کاربر منتظر می‌ماند تا نتیجه تحلیل آماده شود؛ در غیر این صورت، تقاضای تحلیل دریافت می‌شود و کاربر با استفاده از واسط «وضعیت سند» از میزان پیشرفت تحلیل مطلع می‌شود. به این ترتیب پس از پایان پردازش، تقاضای جدیدی برای پردازش سند ارسال می‌شود و این بار تقاضا با نتیجه مناسب پاسخ داده می‌شود.

    + Body

            {
              "page_urls": ["http://bayanbox.ir/view/5067853395275628881/boute.pdf@page=1"],
              "fix_orientation": true,
              "word_positions": false,
              "wait": true
            }

+ Response 200 (application/json)

        [{
          "page_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf@page=1",
          "width": 2125,
          "height": 2750,
          "text": "بوته\n\nدرس‌های دانشگاهی معمولا با پروژه‌هابی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها\n...",
          "parts": [
            {
              "type": "text",
              "direction": "rtl",
              "box": "209 305 1711 449",
              "text": "درس‌های دانشگاهی معمولا با پروژه‌هابی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها\n...",
              "lines": [
                {
                  "probability": 1.0,
                  "box": "211 305 1707 57",
                  "text": "درس‌های دانشگاهی معمولا با پروژه‌هایی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها"
                },
                ...
              ]
            },
            ...
          ]
        }]


## وضعیت سند [/api/document_status/]

<div dir=rtl>
این تابع برای هر کدام از سندهای ورودی مشخص می‌کند که چه تعداد از صفحات آنها تحلیل شده است.
</div>

### نمونه [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
              "document_urls": ["http://bayanbox.ir/view/5067853395275628881/boute.pdf"]
            }

+ Response 200 (application/json)

        {
          "http://bayanbox.ir/view/5067853395275628881/boute.pdf": {
            "analyzed": true,
            "processed_pages": 2,
            "all_pages": 2
          }
        }


## صفحات سند [/api/document_pages/]

<div dir=rtl>
نویسه‌خوان برای تحلیل سند، ابتدا باید آن را صفحه‌صفحه کند. این تابع، فایل سند را در قالب PDF دریافت می‌کند و صفحات آن را به عنوان نتیجه باز می‌گرداند. بعد از این مرحله، تابع «خواندن صفحه» می‌تواند هر کدام از صفحه‌های سند را تحلیل کند.
</div>

### نمونه [POST]

<div dir=rtl>
می‌توانید برای همین تابع، فایل سند را به طور مستقیم و در قالب تقاضای <code>multipart/form-data</code> ارسال نمایید:
</div>

> curl -X POST --header "Authorization: Token TOKEN_KEY" -F "document=@example.pdf" http://alefba.roshan-ai.ir/api/document_pages

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
              "document_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf"
            }

+ Response 200 (application/json)

        {
          "document_url":"http://bayanbox.ir/view/5067853395275628881/boute.pdf",
          "pages": [
            "http://bayanbox.ir/view/5067853395275628881/boute.pdf@page=1",
            "http://bayanbox.ir/view/5067853395275628881/boute.pdf@page=2"
          ]
        }


## دریافت فایل ورد [/api/download_word/]

<div dir=rtl>
با استفاده از این تابع می‌توانید نتیجه صفحات پردازش شده را در قالب فایل Microsoft Word دریافت نمایید. در فایل خروجی، قالب سند حفظ شده است و اجزای متن شامل خطوط، پاراگراف‌ها و خانه‌های جدول در جای خود قرار گرفته‌اند.
</div>

### نمونه [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
              "document_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf"
            }

+ Response 200 (application/msword)

    + Header

            Content-Disposition: attachment; filename=Alefba.docx

    + Body


## دریافت فایل اکسل [/api/download_excel/]

<div dir=rtl>
با استفاده از این تابع می‌توانید نتیجه صفحات پردازش شده را در قالب فایل Microsoft Excel دریافت نمایید. دقت کنید که برای استفاده از این خروجی لازم است در هنگام خواندن سند، ویژگی <code>type</code> را برابر مقدار <code>excel</code> قرار دهید.
</div>

### نمونه [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
              "document_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf"
            }

+ Response 200 (application/msword)

    + Header

            Content-Disposition: attachment; filename=Alefba.xlsx

    + Body


## دریافت فایل قابل جستجو [/api/download_pdf/]

<div dir=rtl>
با استفاده از این تابع می‌توانید نتیجه صفحات پردازش شده را در قالب فایل PDF دریافت نمایید. فایل خروجی، تصاویر صفحات سند ورودی را به همراه نتیجه پردازش آنها نشان می‌دهد. به این ترتیب با جستجوی یک عبارت در این فایل، واژه‌های مورد جستجو در تصویر مشخص و رنگی می‌شوند.
</div>

### نمونه [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
              "document_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf",
              "quality": 100,
              "img_format": "png"
            }

+ Response 200 (application/pdf)

    + Header

            Content-Disposition: attachment; filename=Alefba.pdf

    + Body


## حذف سند [/api/delete_document/]

<div dir=rtl>
با استفاده از این تابع می‌توانید سند ثبت شده در سامانه را به طور کامل حذف کنید.
</div>

### نمونه [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Body

            {
              "document_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf"
            }

+ Response 200 (application/json)

        {
          "message":"Document deleted successfully."
        }

## خواندن سند نامتقارن [/api/read_document/]

<div dir=rtl>
این قابلیت برای جلوگیری از انتظار برای تحلیل فایل قرار داده شده است. پس  از ارسال رکوئست وضعیت فایل در حال تحلیل قرار گرفته و پس اتمام تحلیل رکوئست کالبک حاوی اطلاعات فایل به آدرس وارد شده فرستاده میشود. 
 </div>

### نمونه [POST]

> curl --request POST --header "Content-Type: application/json" --header "Authorization: Token TOKEN_KEY" --data-binary '{"document_url": "DocumentUrl", "callback_url": "CallbackUrl"}' http://alefba.roshan-ai.ir/api/read_document/

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY
            Content-Type: application/json

    + Body

            {
            "document_url": "http://alefba.roshan-ai.ir/media/files/46/00/166072370361-internship.pdf",
            "callback_url": "http://192.168.254.3:5013/alefba_post"  
            }

+ Response 200 (application/json)

        {"state":"processing","document_url":"http://192.168.254.3:5013/static/2021-10-12%20%281%29.png"}
