
FORMAT: 1A
HOST: https://alefba.roshan-ai.ir

# الفبا

الفبا، یک OCR API بسیار کم‌خطا برای استخراج متن‌های فارسی، عربی و انگلیسی از تصاویر است.  

برای دسترسی به ای‌پی‌آی، به یک <code>TOKEN_KEY</code> نیاز دارید که می‌توانید از طریق ایمیلِ alefba@roshan-ai.ir درخواست دهید.

## استخراج متن یک فایل [/api/read_document/]

این تابع، یک فایل تصویری (jpg, png, pdf و...) را به عنوان ورودی می‌گیرد و در پاسخ، متنِ آن را به تفکیک صفحات، پاراگراف‌ها و سطرها به‌همراه اندازه و موقعیت مکانی هریک، به شکل JSON تحویل می‌دهد. الفبا فرق بین جداول و تصاویر و متن‌ها را می‌فهمد و هر یک از این انواع را به شکل مناسب در خروجی ارائه می‌دهد. 

در پاسخ دریافتی، <code>height</code> و <code>width</code> یعنی ارتفاع و عرض صفحه به پیکسل، <code>direction</code> یعنی جهت متن، <code>probability</code> یعنی دقت تشخیص ( مقدارش بین <code>۰</code> و <code>۱</code> است؛ ۱ یعنی دقت تشخیص ۱۰۰٪). <code>box</code> یعنی موقعیت مکانی و اندازهٔ محدودهٔ تشخیص؛ مثلاً "449   1711   305   209" یعنی ۲۰۹ پیکسل فاصله از چپ، ۳۰۵ پیکسل فاصله از بالا، ۱۷۱۱ عرض باکس و 449 ارتفاع باکس.

### مثال: ارسال لینک فایل به‌شکل همگام [POST]

منظور از ارسال همگام این است که تا آماده‌شدن نتیجه منتظر بمانید. برای این منظور باید مقدار پارامتر <code>wait</code> در درخواست ارسالی برابر <code>true‌</code> قرار گیرد که البته مقدار پیش‌فرض نیز همین است. در پاسخ ارسالی، نتیجهٔ پردازش ارائه می‌شود.

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Attributes
        - document_url: URL (string, required) - لینک فایل ورودی
        - type: general (enum[string]) - نوع فایل ورودی. مقدار پیش‌فرض: <code>general</code>.
            + Members
                + `general` - عمومی
                + `ID-card` - کارت‌های شناسایی
                + `excel` - جداول
        - fix_orientation: true (boolean) - اگر <code>true</code> باشد، اعوجاج و کجی تصاویر اصلاح می‌شود. مقدار پیش‌فرض: <code>false</code>.
        - word_positions: true (boolean) - اگر <code>true</code> باشد، استخراج به شکل کلمه‌به‌کلمه و به همراه موقعیت مکانی هر کلمه صورت می‌گیرد. مقدار پیش‌فرض: <code>false</code>.
        - wait: true (boolean) - اگر <code>true</code> باشد، تا زمانی که پردازشِ فایل کامل نشده باید منتظرِ پاسخ بمانید. اگر نمی‌خواهید معطل بمانید این پارامتر را <code>false</code> کنید و هر از گاهی با فرخوانی تابع «بررسی وضعیت پردازش»، میزان پیشرفتِ کار را چک کنید. خوب که پردازش تمام شد، مجدداً درخواست بدهید تا نتیجهٔ پردازش را ببینید. مقدار پیش‌فرض: <code>true</code>.
        - priority: 3 (number) - اولویت پردازش را مشخص می‌کند. <code>۱</code> یعنی خیلی زیاد، <code>۲</code> یعنی زیاد، <code>۳</code> یعنی معمولی، <code>۴</code> یعنی  کم. فقط همین چهار مقدار. مقدار پیش‌فرض: <code>۱</code>.

    + Body

            {
              "document_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf",
              "fix_orientation": true,
              "word_positions": false,
              "type": "general",
              "wait": true,
              "priority": 3
            }

+ Response 200

        {
          "document_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf",
          "pages": [{
            "page_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf@page=1",
            "width": 2125,
            "height": 2750,
            "text": "بوته\n\nدرس‌های دانشگاهی معمولا با پروژه‌هابی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها\n...",
            "parts": [
              {
                "type": "text",
                "direction": "rtl",
                "box": "209 305 1711 449",
                "text": "درس‌های دانشگاهی معمولا با پروژه‌هابی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها\n...",
                "lines": [
                  {
                    "probability": 1.0,
                    "box": "211 305 1707 57",
                    "text": "درس‌های دانشگاهی معمولا با پروژه‌هایی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها"
                  },
                  ...
                ]
              },
              ...
            ]
          },{
            "page_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf@page=2",
            "width": 2125,
            "height": 2750,
            "text": "انجام این کار البته چندان هم آسان نیست؛ نه برای دانشجوها و نه برای کمک‌استادها، اما حاصل بسیار شیرین\n...",
            "parts": [
              {
                "type": "text",
                "direction": "rtl",
                "box": "210 110 1714 294",
                "text": "انجام این کار البته چندان هم آسان نیست؛ نه برای دانشجوها و نه برای کمک‌استادها، اما حاصل بسیار شیرین\n...",
                "lines": [
                  {
                    "probability": 1.0,
                    "box": "210 110 1706 58",
                    "text": "انجام این کار البته چندان هم آسان نیست؛ نه برای دانشجوها و نه برای کمک‌استادها، اما حاصل بسیار شیرین"
                  },
                  ...
                ],
              },
              ...
            ]
          }]
        }

### مثال: ارسال لینک فایل به‌شکل ناهمگام [POST]

منظور از ارسال ناهمگام این است که منتظر نتیجه نمانید. درعوض خودتان با تابع «بررسی وضعیت پردازش» میزان پیشرفت را چک کنید و بعد از کامل‌شدن نتیجه، درخواست مجدد بدهید و نتیجه را ببینید. برای این منظور باید مقدار پارامتر <code>wait</code> در درخواست ارسالی برابر <code>false</code> قرار گیرد. با این کار، بلافاصله بعد از ارسال درخواست، پاسخی با دو پارامتر <code>state</code> (وضعیت پردازش) و <code>task_ids</code> (شناسهٔ پردازش) دریافت می‌کنید که بعداً می‌توانید با تابع «دریافت نتیجهٔ به‌شکل ناهمگام»، خروجی نهایی را با ارائهٔ این شناسه دریافت کنید.

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Attributes

        - document_url: URL (string, required) - لینک فایل ورودی
        - type: general (enum[string]) - نوع فایل ورودی. مقدار پیش‌فرض: <code>general</code>
            + Members
                + `general` - عمومی
                + `ID-card` - کارت‌های شناسایی
                + `excel` - جداول
        - fix_orientation: true (boolean) - اگر <code>true</code> باشد، اعوجاج و کجی تصاویر، اصلاح می‌شود. مقدار پیش‌فرض: <code>false</code>.
        - word_positions: true (boolean) - اگر <code>true</code> باشد، استخراج به شکل کلمه‌به‌کلمه و به همراه موقعیت مکانی هر کلمه صورت می‌گیرد. مقدار پیش‌فرض: <code>false</code>.
        - wait: true (boolean) - اگر <code>true</code> باشد، تا زمانی که پردازشِ فایل کامل نشده باید منتظرِ پاسخ بمانید. اگر نمی‌خواهید معطل بمانید این پارامتر را <code>false</code> کنید و هر از گاهی با فرخوانی تابع «بررسی وضعیت پردازش»، میزان پیشرفتِ کار را چک کنید. خوب که پردازش تمام شد، مجدداً درخواست پردازش فایل بدهید تا نتیجهٔ پردازش را ببینید. مقدار پیش‌فرض: <code>true</code>.
        - priority: 3 (number) - اولویت پردازش را مشخص می‌کند. <code>۱</code> یعنی خیلی زیاد، <code>۲</code> یعنی زیاد، <code>۳</code> یعنی معمولی، <code>۴</code> یعنی  کم. فقط همین چهار مقدار. مقدار پیش‌فرض: <code>۱</code>.

    + Body

            {
              "document_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf",
              "fix_orientation": true,
              "word_positions": false,
              "type": "general",
              "wait": false,
              "priority": 3
            }

+ Response 200
      {
        "state":"PENDING",
        "task_ids": "..."
      }


### مثال: دریافت نتیجه با دادن شناسهٔ پردازش [POST]

در درخواست به‌شکل ناهمگام (یعنی <code>wait</code>=<code>false</code>)، به شما یک <code>task_id</code> داده می‌شود که شناسهٔ پردازش است. برای دریافت نتیجهٔ پردازش، این شناسه را در پارامتر <code>task_id</code> قرار دهید و درخواست خود را ارسال کنید. اینجا نیز می‌توانید در درخواست خود، پارامتر <code>wait</code> را مقداردهی کنید. اگر <code>wait</code> برابر <code>true</code> باشد (مقدار پیش‌فرض) دوحالت پیش می‌آید. یا پردازش کامل شده که نتیجه برمی‌گردد، یا تمام نشده که باید منتظر بمانید. اگر <code>wait</code> را برابر <code>false</code> قرار دهید دوحالت پیش می‌آید. یا پردازش کامل شده که نتیجه برمی‌گردد یا کامل نیست که پاسخی با پارامتر <code>state</code> برمی‌گردد. <code>state</code> بیانگر وضعیت پردازش است.

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

   + Attributes

        - task_id: ID (number, required) - شناسهٔ پردازش
        - wait: true (boolean) - توضیح این پارامتر در شرح این متد آمده است

    + Body

            {
              "task_id": "...",
              "wait": false
            }

+ Response 200
      {
        "state":"started",
        "task_id": "..."
      }

### مثال: ارسال مستقیم فایل [POST]

+ Request (multipart/form-data; boundary={boundary value})

    + Headers

            Authorization: Token TOKEN_KEY

    + Attributes

        - document: file in binary (string, required) - فایل ورودی
        - type: general (enum[string]) - نوع فایل ورودی. مقدار پیش‌فرض: <code>general</code>
            + Members
                + `general` - عمومی
                + `ID-card` - کارت‌های شناسایی
                + `excel` - جداول
        - fix_orientation: true (boolean) - اگر <code>true</code> باشد، اعوجاج و کجی تصاویر، اصلاح می‌شود. مقدار پیش‌فرض: <code>false</code>.
        - word_positions: true (boolean) - اگر <code>true</code> باشد، استخراج به شکل کلمه‌به‌کلمه و به همراه موقعیت مکانی هر کلمه صورت می‌گیرد. مقدار پیش‌فرض: <code>false</code>.
        - wait: true (boolean) - اگر <code>true</code> باشد، تا زمانی که پردازشِ فایل کامل نشده باید منتظرِ پاسخ بمانید. اگر نمی‌خواهید معطل بمانید این پارامتر را <code>false</code> کنید و هر از گاهی با فرخوانی تابع «بررسی وضعیت پردازش»، میزان پیشرفتِ کار را چک کنید. خوب که پردازش تمام شد، مجدداً درخواست پردازش فایل بدهید تا نتیجهٔ پردازش را ببینید. مقدار پیش‌فرض: <code>true</code>.
        - priority: 3 (number) - اولویت پردازش را مشخص می‌کند. ۱ یعنی خیلی زیاد، ۲ یعنی زیاد، ۳ یعنی معمولی، ۴ یعنی  کم. فقط همین چهار مقدار. مقدار پیش‌فرض: <code>۱</code>.

    + Body

            --{boundary value}
            Content-Disposition: form-data; name='document'; filename='FILE NAME'
            Content-Type: text/plain (according to the type of the uploaded file)

            {file content}
            --{boundary value}


+ Response 200
        {
          "pages": [{
            "page_url": "http://alefba.roshan-ai.ir/media/files/96/84/859267728361-boute.pdf@page=1",
            "width": 2125,
            "height": 2750,
            "text": "بوته\n\nدرس‌های دانشگاهی معمولا با پروژه‌هابی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها\n...",
            "parts": [
              {
                "type": "text",
                "direction": "rtl",
                "box": "209 305 1711 449",
                "text": "درس‌های دانشگاهی معمولا با پروژه‌هابی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها\n...",
                "lines": [
                  {
                    "probability": 1.0,
                    "box": "211 305 1707 57",
                    "text": "درس‌های دانشگاهی معمولا با پروژه‌هایی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها"
                  },
                  ...
                ]
              },
              ...
            ]
          },{
            "page_url":"http://alefba.roshan-ai.ir/media/files/96/84/859267728361-boute.pdf@page=2",
            "width": 2125,
            "height": 2750,
            "text": "انجام این کار البته چندان هم آسان نیست؛ نه برای دانشجوها و نه برای کمک‌استادها، اما حاصل بسیار شیرین\n...",
            "parts": [
              {
                "type": "text",
                "direction": "rtl",
                "box": "210 110 1714 294",
                "text": "انجام این کار البته چندان هم آسان نیست؛ نه برای دانشجوها و نه برای کمک‌استادها، اما حاصل بسیار شیرین\n...",
                "lines": [
                  {
                    "probability": 1.0,
                    "box": "210 110 1706 58",
                    "text": "انجام این کار البته چندان هم آسان نیست؛ نه برای دانشجوها و نه برای کمک‌استادها، اما حاصل بسیار شیرین"
                  },
                  ...
                ],
              },
              ...
            ]
          }],
          "document_url":"http://alefba.roshan-ai.ir/media/files/96/84/859267728361-boute.pdf"
        }

## استخراج متن صفحات مشخصی از یک فایل [/api/read_pages/]

درست همانند تابع «ارسال لینک مستقیم فایل» است با این تفاوت که اینجا به جای لینک کاملِ فایل، لینک صفحات مشخصی از فایل را می‌دهید. برای این منظور به انتهای لینک فایل، شمارهٔ صفحه را اضافه کنید. برای مثال وقتی آرایهٔ <code>page_urls</code> برابر "dl.com/book.pdf@page=1‌ و dl.com/book.pdf@page=5" است، صفحات ۱ و ۵ از book.pdf پردازش شده و متنِ آن تحویل داده می‌شود.

### مثال [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Attributes

        - page_urls: URL (array[string], required) - لینک صفحات.
        - type: general (enum[string]) - نوع فایل ورودی. مقدار پیش‌فرض: <code>general</code> 
            + Members
                + `general` - عمومی
                + `ID-card` - کارت‌های شناسایی
                + `excel` - جداول
        - fix_orientation: true (boolean) - اگر <code>true</code> باشد، اعوجاج و کجی تصاویر، اصلاح می‌شود. مقدار پیش‌فرض: <code>false</code>.
        - word_positions: true (boolean) - اگر <code>true</code> باشد، استخراج به شکل کلمه‌به‌کلمه و به همراه موقعیت مکانی هر کلمه صورت می‌گیرد. مقدار پیش‌فرض: <code>false</code>.
        - wait: true (boolean) - اگر <code>true</code> باشد، تا زمانی که پردازشِ فایل کامل نشده باید منتظرِ پاسخ بمانید. اگر نمی‌خواهید معطل بمانید این پارامتر را <code>false</code> کنید و هر از گاهی با فرخوانی تابع «بررسی وضعیت پردازش»، میزان پیشرفتِ کار را چک کنید. خوب که پردازش تمام شد، مجدداً درخواست پردازش فایل بدهید تا نتیجهٔ پردازش را ببینید. مقدار پیش‌فرض: <code>true</code>.
        - priority: 3 (number) - اولویت پردازش را مشخص می‌کند. <code>۱</code> یعنی خیلی زیاد، <code>۲</code> یعنی زیاد، <code>۳</code> یعنی معمولی، <code>۴</code> یعنی  کم. فقط همین چهار مقدار. مقدار پیش‌فرض: <code>۱</code>.

    + Body

            {
              "page_urls": ["http://bayanbox.ir/view/5067853395275628881/boute.pdf@page=1"],
              "fix_orientation": true,
              "word_positions": false,
              "wait": true,
              "priority": 3
            }

+ Response 200

        [{
          "page_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf@page=1",
          "width": 2125,
          "height": 2750,
          "text": "بوته\n\nدرس‌های دانشگاهی معمولا با پروژه‌هابی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها\n...",
          "parts": [
            {
              "type": "text",
              "direction": "rtl",
              "box": "209 305 1711 449",
              "text": "درس‌های دانشگاهی معمولا با پروژه‌هابی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها\n...",
              "lines": [
                {
                  "probability": 1.0,
                  "box": "211 305 1707 57",
                  "text": "درس‌های دانشگاهی معمولا با پروژه‌هایی همراه هستند که سهم قابل‌توجهی از آموزش را بر عهده دارند. این پروژه‌ها"
                },
                ...
              ]
            },
            ...
          ]
        }]


## بررسی وضعیت پردازش [/api/document_status/]

این تابع برای هریک از لینک‌های ورودی مشخص می‌کند که چه تعداد از صفحات آن‌ها پردازش شده است. در پاسخ ارسالی، برای هر لینک، سه پارامتر <code>processed_pages</code> به معنی تعداد صفحات پردازش‌شده، <code>all_pages</code> تعداد کل صفحات و <code>analyzed</code> ارائه می‌شود که پارامتر آخر تنها زمانی <code>true</code> می‌شود که پردازش همهٔ صفحات تمام شده باشد.

### مثال [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Attributes

        - document_urls: URL (array[string], required) - لینک فایل‌ها
 
    + Body

            {
              "document_urls": ["http://bayanbox.ir/view/5067853395275628881/boute.pdf"]
            }

+ Response 200

        {
          "http://bayanbox.ir/view/5067853395275628881/boute.pdf": {
            "analyzed": true,
            "processed_pages": 2,
            "all_pages": 2
          }
        }


## دریافت لینک صفحات سند [/api/document_pages/]

پیش از پردازش فایل ابتدا تمام صفحات آن استخراج می‌شود. این تابع با دریافت لینک فایل، لینک صفحات آن را به شما تحویل می‌دهد.

### مثال [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Attributes

        - document_url: URL (string, required) - لینک فایل ورودی
 
    + Body

            {
              "document_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf"
            }

+ Response 200

        {
          "document_url":"http://bayanbox.ir/view/5067853395275628881/boute.pdf",
          "pages": [
            "http://bayanbox.ir/view/5067853395275628881/boute.pdf@page=1",
            "http://bayanbox.ir/view/5067853395275628881/boute.pdf@page=2"
          ]
        }


## دریافت فایل ورد [/api/download_word/]

این تابع، نتیجهٔ پردازش را در قالب یک فایل ورد به شما تحویل می‌دهد. در این فایل، قالب سند حفظ شده است و اجزایی چون خطوط، پاراگراف‌ها و جداول به‌شکل صحیح درج می‌شود. دقت داشته باشید فایلی که می‌خواهید نسخهٔ وردِ آن را دریافت کنید ابتدا باید با تابع «ارسال لینک مستقیم فایل» پردازش شده باشد. شما نمی‌توانید فایلی که قبلاً پردازش نشده را به ورد تبدیل کنید.

### مثال [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Attributes

        - document_url: URL (string, required) - لینک فایل ورودی

    + Body

            {
              "document_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf"
            }

+ Response 200

    boute.docx file


## دریافت فایل اکسل [/api/download_excel/]

این تابع، نتیجهٔ پردازش را در قالب یک فایل اکسل به شما تحویل می‌دهد. دقت داشته باشید فایلی که می‌خواهید نسخهٔ اکسلِ آن را دریافت کنید ابتدا باید با تابع «ارسال لینک مستقیم فایل» پردازش شده باشد و حتماً پارامتر <code>type</code> آن برابر مقدار <code>excel</code> باشد.

### مثال [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Attributes

        - document_url: URL (string, required) - لینک فایل ورودی

    + Body

            {
              "document_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf"
            }

+ Response 200

    boute.xlsx file

## دریافت PDF قابل جستجو [/api/download_pdf/]

در حالت عادی بسیاری از فایل‌های پی‌دی‌افِ فارسی قابل جستجو نیستند. این تابع نتیجهٔ فایل پردازش‌شده را در قالب یک پی‌دی‌افِ قابل جستجو تحویل می دهد. به این ترتیب با هر یک از نرم‌افزارهای پی‌دی‌اف‌خوانِ رایج می‌توانید کلمات موردنظر را در متن پی‌دی‌اف جستجو کنید. دقت داشته باشید قبل از استفاده از این تابع ابتدا باید با تابع «ارسال لینک مستقیم فایل»، فایل موردنظر را پردازش کرده باشید.

### مثال [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Attributes

        - document_url: URL (string, required) - لینک فایل ورودی
        - quality: 100 (number) - مقدار dpi فایل خروجی. بین <code>۰</code> تا <code>۱۰۰</code>. مقدار پیش‌فرض: <code>۱۰۰</code>.
        - color: false (boolean) - اگر <code>true</code> باشد، فایل خروجی رنگی خواهد بود. مقدار پیش‌فرض: <code>true</code>.

    + Body

            {
              "document_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf",
              "quality": 100,
              "img_format": "png",
              "color": false
            }

+ Response 200

    boute.pdf file

## حذف فایل [/api/delete_document/]

با این تابع می‌توانید فایلی را که قبلاً از طریق تابع «ارسال لینک مستقیم فایل» ارسال کرده‌اید حذف کنید. کافی است دوباره همان لینک را از طریق این تابع ارسال کنید.

### مثال [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Attributes

        - document_url: URL (string, required) - لینک فایل ورودی

    + Body

            {
              "document_url": "http://bayanbox.ir/view/5067853395275628881/boute.pdf"
            }

+ Response 200

        {
          "message":"Document deleted successfully."
        }

## دریافت نتیجهٔ پردازش از طریق کال‌بک [/api/read_document/]

به کمک این تابع می‌توانید فایل موردنظر را به‌همراه یک کال‌بک ارسال کنید تا هروقت پردازش کامل شد نتیجه به آن کال‌بک ارسال شود. با این روش دیگر نیازی نیست منتظر پردازش فایل بمانید یا دیگر لازم نیست از طریق تابع «بررسی وضعیت پردازش»، میزان پیشرفت پردازش را چک کنید. 

### مثال [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY
            Content-Type: application/json

    + Attributes

        - document_url: URL (string, required) - لینک فایل ورودی
        - callback_url: URL (string, required) - لینک کال‌بک برای ارسال نتیجه

    + Body

            {
              "document_url": "http://alefba.roshan-ai.ir/media/files/46/00/166072370361-internship.pdf",
              "callback_url": "http://192.168.254.3:5013/alefba_post"
            }

+ Response 200

        {
          "state":"processing",
          "document_url":"http://192.168.254.3:5013/static/2021-10-12%20%281%29.png"
        }
