FORMAT: 1A
HOST: https://fahm.roshan-ai.ir/api/

# فهم

این ای‌پی‌آی برای انجام عملیات ترجمه، خلاصه‌سازی و گفت‌وگو طراحی شده است.

## خلاصه‌سازی اسناد ذخیره‌شده [/barid/summarize/]
### خلاصه‌سازی با شناسه سند [POST]

این ای‌پی‌آی برای خلاصه‌سازی اسنادی که از قبل در ایندکس‌های ذخیره‌سازی قرار دارند استفاده می‌شود.

**پارامترها:**
<code>id</code> (لیست): شناسه‌های اسناد موردنظر.
<code>index</code> (رشته): ایندکس محل ذخیره‌سازی اسناد.
<code>type</code> (رشته): نوع سند (مثلاً "نامه").
<code>content_key</code> (رشته): کلید محتوای اصلی (مثلاً "body").
<code>type</code> (رشته): نوع خلاصه‌سازی. مقادیر قابل قبول: `word`, `conversation`, `bullet`.
<code>level</code> (رشته): سطح خلاصه‌سازی. مقادیر قابل قبول: `level_1`, `level_2`, `level_3`.

+ Request (application/json)

    + Headers

            Authorization: Token YOUR_API_TOKEN
            Content-Type: application/json

    + Body

            {
                "baaz_documents": [
                    {
                        "index": "pargar-6b8e75e2-e4e6-42fc-9e6a-818239fe8f58",
                        "type": "نامه",
                        "id": "ed47bf9c-0102-4a95-a9e6-dff362f3b276",
                        "content_key": "body"
                    },
                    {
                        "index": "pargar-6b8e75e2-e4e6-42fc-9e6a-818239fe8f58",
                        "type": "پست",
                        "id": "b44cdd93-fe37-4a5d-8ae8-e58d549668aa",
                        "content_key": "body"
                    }
                ],
                "type": "word",
                "level": "level_1"
            }

+ Response 200 (application/json)

            {
                "summarized_result": "جناب آقای غلامرضا صادقزاده تست کننده مهلت 22/02/1404. محمدرضا اوبایی، مالک محصول، به عنوان مدیر تست امضاهای 1 تا 20 را دارد."
            }

## درک مطلب اسناد ذخیره‌شده [/barid/comprehension/]
### پاسخ به سوالات بر اساس اسناد ایندکس‌شده [POST]

این ای‌پی‌آی برای پاسخ به سوالات بر پایه‌ی اسنادی که از قبل در ایندکس مشخصی ذخیره شده‌اند استفاده می‌شود. با ارسال شناسه سند (یا چند سند)، ایندکس مربوطه، نوع سند و لیستی از سوالات، سیستم پاسخ‌های متنی را از دل محتوای اسناد استخراج می‌کند.

**پارامترها:**
<code>id</code> (لیست رشته): لیستی از شناسه‌های سند.
<code>index</code> (رشته): نام ایندکس محل ذخیره‌سازی اسناد.
<code>type</code> (رشته): نوع سند (مثلاً "نامه").
<code>content_key</code> (رشته): کلید محتوای مورد تحلیل (مانند "body").
<code>questions</code>: لیستی از سوالات متنی که باید به آن‌ها پاسخ داده شود. هر سوال یک آبجکت است که دارای دو کلید text و type است. 
مقدار text همان سوال است و مقدار type نوع سوال را مشخص میکند که در حالت پیش فرض str است. این مقدار اختیاری است.

+ Request (application/json)

    + Headers

            Authorization: Token YOUR_API_TOKEN
            Content-Type: application/json

    + Body

            {
                "baaz_documents": [
                    {
                        "index": "pargar-6b8e75e2-e4e6-42fc-9e6a-818239fe8f58",
                        "type": "نامه",
                        "id": "ed47bf9c-0102-4a95-a9e6-dff362f3b276",
                        "content_key": "body"
                    },
                    {
                        "index": "pargar-6b8e75e2-e4e6-42fc-9e6a-818239fe8f58",
                        "type": "پست",
                        "id": "b44cdd93-fe37-4a5d-8ae8-e58d549668aa",
                        "content_key": "body"
                    }
                ],
                "questions": [
                    {
                        "text": "امضا ها در چه تاریخی انجام شده اند ؟",
                        "type": "str"
                    },
                    {
                        "text": "چندتا امضا انجام شده ؟"
                    }
                ]
            }

+ Response 200 (application/json)

            {
                "result": [
                    [
                        {
                            "text": "22/02/1404",
                            "score": 1
                        },
                        {
                            "text": 20,
                            "score": 1
                        }
                    ]
                ]
            }
