FORMAT: 1A
HOST: https://fahm.roshan-ai.ir/api

# فهم

این ای‌پی‌آی برای انجام عملیات ترجمه، خلاصه‌سازی و گفت‌وگو طراحی شده است.

برای استفاده از این ای‌پی‌آی نیازمند توکن هستید. این توکن را از بخش فروش دریافت کنید.

## ترجمه [/translation/]

یک متن را از انگلیسی به فارسی یا از فارسی به انگلیسی ترجمه می‌کند. زبان‌های دیگر پشتیبانی نمی‌شود.

### ترجمه متن انگلیسی به فارسی [POST]

+ Request (application/json)

    + Headers

            Authorization: Token YOUR_API_TOKEN
    
    + Attributes
        - text: - (string, required) - متنی که باید ترجمه شود.
        - to: - (enum[string], required) -  به کدام زبان ترجمه شود؟
            + Members
                + en - انگلیسی
                + fa - فارسی
    
    + Body

            {
                "text":"Hello. How are you?",
                "to":"fa"
            }


+ Response 200 (application/json)

            {
                "result": "```\nسلام. چطوری؟\n```"
            }
            
### ترجمه متن فارسی به انگلیسی [POST]

+ Request (application/json)

    + Headers

            Authorization: Token YOUR_API_TOKEN
    
    + Attributes
        - text: - (string, required) - متنی که باید ترجمه شود.
        - to: - (enum[string], required) -  به کدام زبان ترجمه شود؟
            + Members
                + en - انگلیسی
                + fa - فارسی
    
    + Body

            {
              "text": "به نام خداوند بخشنده مهربان",
              "to": "en"
            }


+ Response 200 (application/json)

            {
                "result": "```\nIn the name of the Lord, the Forgiving, the Merciful\n```"
            }
            

### ترجمه سند از انگلیسی به فارسی [POST]

+ Request (application/json)

    + Headers

            Authorization: Token YOUR_API_TOKEN
    
    + Attributes
        - document_url: - (string, required) - آدرس سندی که باید ترجمه شود روی سامانه الفبا.
        - to: - (enum[string], required) -  به کدام زبان ترجمه شود؟
            + Members
                + en - انگلیسی
                + fa - فارسی
    
    + Body

            {
                "document_url": "http://alefba-dev.roshan-ai.ir/media/files/37/01/sample_en.txt",
                "to": "fa",
            }


+ Response 200 (application/json)

            {
              "result": "```\nسلام. چطوری؟\n```"
            }
            
### ترجمه سند از فارسی به انگلیسی [POST]

+ Request (application/json)

    + Headers

            Authorization: Token YOUR_API_TOKEN
    
    + Attributes
        - document_url: - (string, required) - آدرس سندی که باید ترجمه شود روی سامانه الفبا.
        - to: - (enum[string], required) -  به کدام زبان ترجمه شود؟
            + Members
                + en - انگلیسی
                + fa - فارسی
    
    + Body

            {
                "document_url": "http://alefba-dev.roshan-ai.ir/media/files/37/01/sample_fa.txt",
                "to": "fa",
            }


+ Response 200 (application/json)

            {
                "result": "```\nIn the name of the Lord, the Forgiving, the Merciful\n```"
            }

## خلاصه‌سازی [/summarization/]

یک متن را به صورت معمولی یا به صورت یک فهرست یا در قالب یک گفتگو خلاصه می‌کند. همچنین امکان تعیین میزان حجم خلاصه در سه سطح کم، متوسط و زیاد وجود دارد.

### خلاصه‌سازی متنی [POST]

+ Request (multipart/form-data)

    + Headers

            Authorization: Token YOUR_API_TOKEN
            
    + Attributes
        - text: - (string, required) - متنی که باید خلاصه شود.
        - type: - (enum[string], required) -  در چه قالبی خلاصه شود؟
            + Members
                + word - معمولی
                + bullet - فهرست‌وار
                + conversation - گفتگو
                
        - level: - (enum[string], required) - ح حجم خلاصه چقدر باشد؟ در حالت conversation فقط level_1 قابل قبول است.
            + Members
                + level_1 - کم
                + level_2 - متوسط
                + level_3 - زیاد

    + Body

            {
                "text": "سلام، وقت شما بخیر؛ وقت شما هم بخیر، امیدوارم حال‌تان خوب باشد؛ سپاسگزارم، بله متشکرم، امیدوارم حال شما هم مساعد باشد؛ بله، ممنون از لطفتان، در خدمت هستم؛ خواستم درباره جلسه‌ی فردا با شما هماهنگ کنم؛ بله حتماً، چه ساعتی مد نظر دارید؟ اگر موافق باشید ساعت ده صبح مناسب است؛ بله، زمان مناسبی‌ست، مکان جلسه همان دفتر مرکزی خواهد بود؟ بله، طبق برنامه در دفتر مرکزی برگزار می‌شود؛ بسیار خوب، حتماً رأس ساعت ده در محل حاضر خواهم بود؛ سپاسگزارم از همکاری شما، اگر موردی بود در تماس خواهم بود؛ خواهش می‌کنم، بنده هم در صورت نیاز اطلاع خواهم داد، روز خوش؛ همچنین، روزتان بخیر و به امید دیدار.",
                "type": "word",
                "level": "level_1"
            }

+ Response 200 (application/json)

            {
                "result": "جلسه فردا ساعت ده صبح در دفتر مرکزی قرار گرفته است. هر دو طرف به زمان و مکان اعلام شده موافقت کرده‌اند. پیام‌ها با لحن مهربانی و احترام پایان یافته است."
            }
