
FORMAT: 1A
HOST: http://api.sobhe.ir

# Parde

پرده تصاویر نامناسب را تشخیص می‌دهد.

برای دسترسی به واسط برنامه‌نویس پرده نیاز به یک TOKEN_KEY معتبر دارید که برای احراز هویت استفاده می‌شود. لطفا برای آزمایش سامانه، این متغیر را در تقاضاهای نمونه، جای‌گذاری کنید. سوال هم اگر دارید، لطفا برای آدرس parde@roshan-ai.ir بنویسید.


## تحلیل تصاویر [/parde/api/tag_images]

### Request [POST]

با استفاده از این تابع می‌توانید برای برچسب‌های مربوط به تصاویر مورد نظر خود را از پرده بپرسید. برچسب‌های تصاویر شامل لیستی آیتم‌هاست که هر آیتم شامل آدرس تصویر، و لیستی از برچسب‌هاست که هر برچسب شامل نام برچسب و عددی بین ۰ و ۱ به عنوان میزان اطمینان از برچسب، می‌باشد.
برای بازدهی بهتر می‌توانید برچسب چند تصویر را در یک درخواست از پرده بپرسید.

+ Request (application/json)

    + Headers
       
            Authorization: Token TOKEN_KEY
    
    + Attributes

        - image_urls: URL (array[string], required) - لیست آدرس تصاویر
 
    + Body

            {
                "image_urls": [
                    "http://www.sobhe.ir/baaz/img/goshawk.jpg"
                ]
            }

+ Response 200 (application/json)

        [{"image_url":"http://www.sobhe.ir/baaz/img/goshawk.jpg","tags":[]}]


## فریم‌های کلیدی ویدئو [/parde/api/tag_video_frames]

 با استفاده از این تابع می‌توانید برچسب مربوط به فریم‌های کلیدی یک ویدئو را از پرده بپرسید. پاسخ سرور لیستی از فریم‌ها به همراه برچسب مربوط به آن‌ها می‌باشد.

### Request [POST]

+ Request (application/json)

    + Headers

            Authorization: Token TOKEN_KEY

    + Attributes

        - video_urls: URL (array[string], required) - لیست آدرس ویدئو‌ها
        - every_ms: 100 (number) - فاصله بین دو فریم استخراج شده به میلی ثانیه
        - min_frame_diff: 0.4 (number) - حداقل تفاوت میان دو فریم که به عنوان فریم مستقل در نظر گرفته شوند.
        - duration: 25 (number) - مقدار زمان به ثانیه از ابتدا ویدئو که پردازش روی آن انجام می‌شود. اگر Null باشد کل ویدئو پردازش خواهد شد.
        - wait: true (boolean) - اگر این پارامتر فعال باشد، درخواست به صورت غیرهم‌گام ارسال شده و در حین پردازش ویدئو سرور با عبارت 'pending' یا 'started' پاسخ می‌دهد. در اولین درخواست پس از پایان فرآیند پردازش ویدئو، سرور نتیجه پردازش را ارسال می‌کند.

            {
                video_urls: ["https://hajifirouz6.cdn.asset.aparat.cloud/aparat-video/2a6a6ecede3579f0f58bd99d37cfa9ef42917772-240p.mp4"],
                every_ms: 200, 
                duration: 36000, 
                min_frame_diff: 0.5
            }

+ Response 200 (application/json)

        [{"video_url":"https://hajifirouz6.cdn.asset.aparat.cloud/aparat-video/2a6a6ecede3579f0f58bd99d37cfa9ef42917772-240p.mp4","frames":[{"frame":6,"time":"0:00:00","tags":[]},{"frame":31,"time":"0:00:01","tags":[]},{"frame":36,"time":"0:00:01","tags":[]},...,{"frame":475,"time":"0:00:18","tags":[{"id":86141,"probability":0.32,"title":"خشونت"}]},{"frame":560,"time":"0:00:22","tags":[]},...]}]
