
FORMAT: 1A
HOST: https://kashf.roshan-ai.ir

# پرده
پرده یک ای‌پی‌آی بومی برای تشخیص تصاویر نامناسب است.

در روزگار ما دسترسی به فضای مجازی حتی برای کودکان به‌سادگی میسر است. از طرفی می‌دانیم که در این فضا همه نوع محتوایی هست. محتوای نامناسب آسیب‌زاست خصوصاً برای قشر کودک و نوجوان. دولت‌ها تلاش می‌کنند اینترنت را به محیطی سالم و امن تبدیل کنند اما حجم روزافزون داده‌ها در فضای مجازی امکان نظارت انسانی بر این محیط را بسیار سخت کرده است. راه‌حل، استفاده از هوش ماشینی برای پالایش و فیلتر محتواست.

پرده دقیقاً با همین هدف ساخته شده است.

این ابزار، تصاویر و ویدیوهای نامناسب را در چهار دسته شناسایی و گزارش می‌دهد:

از دید پرده، تصویر و ویدیوی نامناسب در یکی از این چهار دسته قرار می‌گیرد:

۱. **برهنه:** تصاویر و ویدیوهایی که به طرز وقیحانه و حیوان‌واری اعضای جنسی انسان را به نمایش می‌گذارند. حتی رسانه‌های غربی نیز در نمایش این نوع محتوا فیلترهای سفت‌وسختی را برای سنین مختلف درنظر گرفته‌اند. همچنین در بسیاری از شبکه‌های اجتماعی نیز انتشار چنین محتوایی خلاف قوانین است.

۲. **نامناسب:** تعریف اسلام از محتوای «نامناسب» بسیار وسیع‌تر از تعریف سطحی غرب است. در اسلام، نامناسب بودن محتوا صرفاً محدود به برهنگی نیست! شاید بتوان ملاک‌های صداوسیما در انتشار محتوا را نزدیک به همان چیزی دانست که شرع مقدس اسلام اجازه داده است. از دید پرده تصویر و ویدیویی «نامناسب» است که با ملاک‌های صداوسیما در تلویزیون ایران قابل پخش نیست.

۳. **وحشتناک:** فقط محتوای غیراخلاقی نیست که بر روان آدمی اثر منفی می‌گذارد. گاهی دیدن صحنه‌ای دلخراش از یک تصادف رانندگی که حاوی آسیب‌های منزجرکننده‌‌ای مثل سوختگی و لهیدگی است می‌تواند همان تأثیر سوء را در پی داشته باشد.

۴. **خشونت:** گاهی تصویر یا ویدیو حاوی صحنه‌های منزجرکننده نیست ولی این موضوع حاکی از وجود یک خشونت است؛ مثلاً آثار خون روی زمین یا دیوار یا فردی که روی زمین افتاده است. این نوع محتوا می‌تواند نشانی از نامناسب‌بودن محتوا برای کودکان باشد.

پرده می‌تواند با یک سخت‌افزار معمولی **هر ثانیه بیش از ۲۰۰ تصویر** را تحلیل و پالایش کند. این رقم را پژوهشکدهٔ ارتباطات و فناوری اطلاعات ایران، بعد از ارزیابی دقیق عملکرد سامانه روی مجموعه‌ای از تصاویر متعدد اعلام کرده است.

برای دسترسی به این ای‌پی‌آی به یک `TOKEN_KEY` نیاز دارید که می‌توانید از طریق ایمیلِ [parde@roshan-ai.ir](mailto:parde@roshan-ai.ir) درخواست دهید

## برچسب‌گذاری تصاویر [/parde/api/tag_images]

### مثال [POST]
ورودی این تابع لیستی از آدرس تصاویر است و خروجی آن برچسب‌های هر تصویر. آنچه در پاسخ برگردانده می‌شود آرایه‌ای از آیتم‌هاست. هر آیتم متشکل از فیلد `image_url` حاوی لینک تصویر و آرایهٔ `tags` حاوی برچسب‌های تصویر است. شناسهٔ هر برچسب در فیلد `id`، عنوان برچسب در فیلد `title`و میزان اطمینان به آن برچسب در فیلد `probability`قرار می‌گیرد.

+ Request (application/json)
    + Headers       
        Authorization: Token TOKEN_KEY    
    + Attributes
        - image_urls: URL (array[string], required) - لیست آدرس تصاویر. 
    + Body
        {
            "image_urls": 
            [
                "https://avaymarz.ir/wp-content/uploads/2020/11/5370736.jpg"
            ]
        }
+ Response 200 (application/json)
    [
        {
            "image_url":"https://avaymarz.ir/wp-content/uploads/2020/11/5370736.jpg",
            "tags": 
            [
                {
                    "probability": 0.5,
                    "title": "خشونت"
                }
            ]
        }
    ]

## برچسب‌گذاری فریم‌های ویدیو [/parde/api/tag_video_frames]
ورودی این تابع لیستی از آدرس ویدیوها است و خروجی آن برچسب‌های هر ویدیو. آنچه در پاسخ برگردانده می‌شود آرایه‌ای از آیتم‌هاست. هر آیتم متشکل از یک فیلد `video_url` حاوی لینک تصویر و آرایهٔ `frames` حاوی فریم‌های پردازش‌شده است. در هر فریم، شمارهٔ آن در فیلد `frame`، موقعیت زمانی آن در فیلد `time` و برچسب‌های شناسایی‌شده برای آن در فیلد `tags` قرار می‌گیرد.

### مثال [POST]
+ Request (application/json)
    + Headers
        Authorization: Token TOKEN_KEY
    + Attributes
        - video_urls: URL (array[string], required) - آدرس ویدیوهایی که می‌خواهید فریم‌های آن برچسب‌گذاری شود.
        - every_ms: 100 (number) - هر چند میلی‌ثانیه یک فریم استخراج شود؟
        - min_frame_diff: 0.4 (number) - کمترین تفاوتِ دو فریم که از آن به بعد یک فریم را متفاوت از قبلی بداند. عددی بین ۰ تا ۱.
        - duration: 25 (number) - چندثانیه از ابتدای ویدیو پردازش شود؟ اگر `null` باشد کل ویدیو پردازش می‌شود.
        - wait: true (boolean) - اگر `true` باشد (مقدار پیش‌فرض)، تا پایان فرایند پردازش باید منتظر بمانید. اگر `false` باشد، بلافاصله بعد از ارسال درخواست، پاسخی با اعلام وضعیتِ `pending` یا `started` ارسال می‌شود و در درخواست‌های بعدی اگر نتیجه آماده بود برگردانده می‌شود و اگر نه همچنان روی `pending` خواهد بود.
    + Body    
        {
            "video_urls": ["sample.com/1.mp4"],
            "every_ms": 200, 
            "duration": 36000, 
            "min_frame_diff": 0.5
        }
+ Response 200 (application/json)
    [
        {
            "video_url": "sample.com/1.mp4",
            "frames": 
            [
                {
                    "frame": 6,
                    "time": "0:00:00",
                    "tags": []
                },
                {
                    "frame": 31,
                    "time": "0:00:01",
                    "tags": []
                },
                {
                    "frame": 36,
                    "time": "0:00:01",
                    "tags": []
                },
                {
                    "frame": 475,
                    "time": "0:00:18",
                    "tags": 
                    [
                        {
                            "id": 86141,
                            "probability": 0.32,
                            "title": "وحشتناک"
                        },
                        {
                            "id": 86142,
                            "probability": 0.49,
                            "title": "برهنه"
                        }
                    ]
                },
                {
                    "frame": 560,
                    "time": "0:00:22",
                    "tags": []
                }
            ]
        }
    ]
