FORMAT: 1A
HOST: https://chat.replai.ir/api

# Repli
Repli is an intelligent conversational assistant. It acts as an always-online support agent, receiving users' messages at any time and, after understanding the message, either selects an appropriate pre-prepared response or generates one for the user. In the demo environment of this project, users can have their dedicated testing space, customize its information, and evaluate it via a graphical interface or API. 
To evaluate the space in the graphical user interface, you must obtain a username and password. For evaluation via API, you need to acquire a connection key from the Roshan sales team.

::: note
## Extensions
**نام کاربری** و **گذرواژه** را از تیم فروش دریافت کنید.
:::

# Group احراز هویت

## ورود [/token-auth]

### دریافت توکن [POST]

::: note
برای استفاده از ای‌پی‌آی ریپلای ابتدا باید `توکن دسترسی` دریافت کنید. این توکن را باید در هیدر تمام درخواست‌های خود وارد کنید.
:::

::: warning
#### <i class="fa fa-warning"></i> اخطار
`نام کاربری`، `گذرواژه` و `توکن دسترسی` را تنها در اختیار افراد مجاز قرار دهید!
:::

### روش استفاده از توکن

روش ارسال توکن در هیدر درخواست‌ها به صورت زیر است:

```no-highlight
Authorization: Token {token}
```

برای مثال اگر توکن دریافتی `abc123XYZ456sampleToken789` باشد، هیدر درخواست شما باید به صورت زیر باشد:

```no-highlight
Authorization: Token abc123XYZ456sampleToken789
```

+ Request (application/json)

    + Attributes

        + username: ali (string, required) - نام کاربری
        + password: 14524785 (string, required) - گذرواژه

+ Response 200 (application/json)

    + Attributes

        + token: abc123XYZ456sampleToken789 (string)
        + first_name: علی (string) - نام
        + last_name: صادقی (string) - نام خانوادگی

+ Response 401 (application/json)

    + Attributes

        + detail: Authentication credentials were not provided. (string)

# Group فضاهای کاری

فضاهای کاری، محیط‌های تستی برای نسخه‌های مختلف ابزار ما هستند که بر اساس رویکردهای مختلف توسعه یافته‌اند یا داده‌های متنوعی را برای پاسخگویی به پرسش‌ها فراهم می‌کنند. در نرم‌افزار تحت‌وبی که در اختیار شما قرار گرفته، شما به یک یا چند فضای کاری دسترسی دارید و هر زمان می‌توانید بین آن‌ها سوئیچ کنید. همچنین از طریق ای‌پی‌آی، امکان مشاهدهٔ اطلاعات فضاهای کاری وجود دارد.

هر فضای کاری دارای این مشخصه‌ها است:
+ id: شناسه فضای کاری
+ title: عنوان فضای کاری
+ version: نسخه فضای کاری. یک فضای کاری ممکن است چند نسخه مختلف داشته باشد
+ image: آدرس تصویر آیکون فضای کاری
+ samples: نمونه پرسش‌های فضای کاری

## فضاهای کاری [/workspaces]

### لیست فضاهای کاری [GET]

+ Request (application/json)

    + Headers
        Authorization: Token abc123XYZ456sampleToken789

+ Response 200 (application/json)
    + Attributes (Workspace)        


# Group چت‌ها
در صورتی که مشتری بخواهد از این سامانه برای پاسخگویی به کاربران خود استفاده کند می تواند از ایجاد رابطه بین چت های سامانه و کاربران خود بهره برداری کند.

## چت‌های یک فضای کاری [/workspaces/{workspace_id}/chats]

+ Parameters

    + workspace_id: `1` (number) - شناسه فضای کاری مورد نظر

### لیست همه چت‌ها [GET]

+ Response 200 (application/json)

    + Attributes (array[Chat])

### ساخت یک چت جدید [POST]

+ Request

    + Body

        {"text":"کدام بانک ها ارز اربعین می‌دهند؟"}

+ Response 200

        {
            "chat_id": 4153,
            "reply": " با مراجعه به شعب منتخب 7 بانک ملی، تجارت، صادرات، ملت، پست بانک، پارسیان و سپه، می‌توانید ارز اربعین را دریافت کنید.",
            "message_id": 29292,
            "suggestions": [
                "ارز اربعین چقدر است و از کدام بانک‌ها می‌توان تهیه کرد؟",
                "چقدر ارز اربعین می‌دهند؟"
            ]
        }

### حذف تمام چت‌ها [DELETE]

+ Response 200

# Group پیام

## پیام‌های یک چت [/chats/{chat_id}/messages]

+ Parameters
    + chat_id: 1 (number) - شناسه چت مورد نظر

### لیست همه پیام‌ها [GET]

+ Response

    + Attributes (array[Message])

### ساخت یک پیام جدید [POST]

+ Request

    + Body

            {
                text: "کدام بانک ها ارز اربعین می‌دهند؟"
            }

+ Response 200

    {
        "message_id": 29293,
        "reply": " با مراجعه به شعب منتخب 7 بانک ملی، تجارت، صادرات، ملت، پست بانک، پارسیان و سپه، می‌توانید ارز اربعین را دریافت کنید.",
        "suggestions": [
            "ارز اربعین چقدر است و از کدام بانک‌ها می‌توان تهیه کرد؟",
            "چقدر ارز اربعین می‌دهند؟"
        ]
    }

# Group بازخورد

## بازخورد یک پیام [/chats/messages/{message_id}/{feedback}]

+ Parameters

    + message_id: `1` (number) - شناسه پیام
    + feedback: `like` (enum[string])
        بازخورد

        + Members
            + `like`
            + `dislike`

### افزودن بازخورد [PUT]

+ Response 200

    + Body

        {
            like: true
        }

### حذف بازخورد [PUT]

+ Response 200


# Group پایگاه دانش

## سوالات پایگاه دانش یک فضای کاری [/knowledge/{workspace_id}/questions{?page,search,order,rate,suggest}]

+ Parameters

    + workspace_id: `12345` (string, required) - شناسه فضای کاری.

### لیست همه سوالات [GET]

+ Parameters

    + workspace_id: `12345` (string, required) - شناسه فضای کاری.
    + page: `1` (number, optional) - شماره صفحه مورد نظر. Default is `1`.
    + search: `""` (string, optional) - متن مورد جستجو. Default is an empty string.
    + order: `-id` (string, optional) - ترتیب چینش سوالات. Default is `-id`.
    + rate: `true` (boolean, optional) - فیلتر سوالات کلیدی.
    + suggest: `true` (boolean, optional) - فیلتر سوالات اصلاح شده.

+ Response 200


        {
            "count": 3009,
            "next": "http://chat.replai.ir/api/knowledge/41/messages/?order=-id&page=2&search=",
            "previous": null,
            "results": [
                {
                    "id": 12607,
                    "question": "امنیت کشور عراق موقع پیاده‌روی اربعین چگونه است؟",
                    "answer": "امنیت کشور عراق در طول پیاده‌روی اربعین به طور کلی مناسب است. تدابیر امنیتی ویژه‌ای برای حفاظت از زائران در نظر گرفته شده و نیروهای امنیتی و امدادی در طول مسیر حضور دارند تا امنیت و رفاه زائران را تضمین کنند. احتمال حمله تروریستی در این ایام بسیار کم است.",
                    "rated": false,
                    "suggested": false,
                    "citation": 0,
                    "references": [
                        "امنیت کشور عراق موقع پیاده روی چکونه است"
                    ]
                },
                {
                    "id": 12606,
                    "question": "موقع پیاده روی اربعین چه ساعتی بهتر است؟",
                    "answer": "بهترین ساعت برای پیاده‌روی اربعین، غروب آفتاب تا نماز صبح است، زیرا در این ساعات خنکی بیشتری وجود دارد.",
                    "rated": false,
                    "suggested": false,
                    "citation": 0,
                    "references": [
                        "موقع پیاده روی چه ساعتی بهتراست"
                    ]
                },
            ]
        }

### اضافه کردن سوال [POST]

+ Parameters

    + workspace_id: `12345` (string, required) - شناسه فضای کاری.

+ Request

    + Body

        {
            "question":"سوال تستی",
            "answer":"جواب تستی",
            "workspace":41
        }

+ Response 200 (application/json)

    {
        "id": 13306,
        "question": "سوال تستی",
        "answer": "جواب تستی",
        "rated": false,
        "suggested": false,
        "citation": 0,
        "references": []
    }

### اصطلاح سوال [PUT]

+ Parameters

    + workspace_id: `12345` (string, required) - شناسه فضای کاری.
    + question_id: `1` (number, required) - شناسه سوال

+ Request

    + Body

        {
            "question":"ارز اربعین چه قدر است و از کدام بانک‌ها می‌توان تهیه کرد؟",
            "answer":"برای هر زائر اربعین ۲۰۰ هزار دینار عراق به عنوان ارز اربعین ۱۴۰۳ اختصاص یافته است. بر اساس ابلاغ بانک مرکزی، زائران اربعین می‌توانند با مراجعه به شعب منتخب ۷ بانک ملی، تجارت، صادرات، ملت، پست بانک، پارسیان و سپه از تاریخ هفتم مرداد ۱۴۰۳ تا پایان روز سوم شهریور ۱۴۰۳، ارز مسافرتی اربعین را برای سفر به کربلا دریافت کنند. برای دریافت ارز اربعین، ثبت نام و دریافت کد رهگیری سامانه سماح ضروری است. این کد رهگیری برای ثبت نام در سامانه‌های اینترنتی بانک های مختلف مورد نیاز است. ",
            "suggest":true
        }

+ Response 200 (application/json)

    {"detail":"ok"}

    
### حذف سوال [DELETE]

+ Parameters

    + workspace_id: `12345` (string, required) - شناسه فضای کاری.
    + question_id: `1` (number, required) - شناسه سوال

+ Response 200

# Group وارد کردن سوال و جواب‌ها از طریق فایل

## آپلود csv به یک فضای کاری [/workspaces/{workspace_id}/upload-qa-csv/]

+ Parameters

    + workspace_id: `12345` (string, required) - شناسه فضای کاری.

### آپلود فایل سوال و جواب‌ها [POST]

+ Request (text/csv)

+ Response 200


# Data Structures

## Workspace (object)
+ id: 8  (number) - شناسه فضای کاری
+ title: بیمه سامان (string) - عنوان فضای کاری
+ version: 0.0.0.1 (string) - نسخه فضای کاری
+ image: saman.png (string) - آدرس تصویر فضای کاری
+ samples (array[Sample])


## Sample (object)
+ text: خرید بیمه تکمیلی بدون بیمه پایه امکان پذیر است؟ (string)

## Chat (object)
+ date: `2024-09-14` (string) - تاریخ چت
+ chats (array[ChatDetail])

## ChatDetail (object)
+ id: 3650 (number) - شناسه چت
+ title: چه کاری انجام میدهی  (string) - عنوان

## Message (object)
+ id: 27073 (number) - شناسه پیام
+ content: لینک خرید ارز اربعین در روبیکا چیست؟ (string) - متن پیام
+ audio: null
+ message_answer: برای خرید ارز اربعین از طریق اپلیکیشن روبیکا، می‌توانید به لینک زیر مراجعه کنید:\n\nhttps://go.rubika.ir/arbaeen1 (string) - پاسخ پیام
+ like: null (string) - وضعیت پسندیده شدن پاسخ پیام
+ created: `2024-09-07T07:48:53.094209Z` (string) - تاریخ ایجاد پیام