FORMAT: 1A
HOST: https://chat.replai.ir/api

# ریپلای
ریپلای یک دستیار گفتگوی هوشمند است که به‌عنوان پشتیبان آنلاین، پیام‌های کاربران را دریافت و با تحلیل دقیق آن‌ها، پاسخ‌های مناسب ارائه می‌دهد. در نسخه دمو، می‌توانید محیط تست اختصاصی خود را ایجاد کنید، آن را به دلخواه شخصی‌سازی کنید و از طریق رابط کاربری گرافیکی یا API عملکرد آن را ارزیابی نمایید. دسترسی به این قابلیت‌ها مستلزم دریافت نام کاربری، گذرواژه یا کلید اتصال از تیم فروش روشن است.
## ورود [/token-auth]

ابتدا نام کاربری و رمز عبوری که در اختیار شما قرار گرفته را در قالب یک درخواست post ارسال کنید تا بتوانید توکن اتصال دریافت کنید. این توکن در تمام درخواست‌های شما بایستی در هیدر آن  درخواست وجود داشته باشد.

### دریافت توکن [POST]

+ Request (application/json)

    {
        "username":"*******",
        "password":"*******"
    }

+ Response 200 (application/json)

    {
        "token": "***********************************",
        "first_name": '*********************',
        "last_name": '**********************'
    }


## فضاهای کاری [/workspaces]

فضای کاری یک محیط ایزوله برای گفتگو با چت‌بات در یک موضوع مشخص است. هر فضای کاری می‌تواند به روش متفاوتی پیاده‌سازی شده باشد، می‌تواند داده‌های متفاوتی داشته باشد، عنوان، تصویر و نمونه پیام‌های متفاوتی داشته باشد.

### لیست فضاهای کاری [GET]

+ Request (application/json)

    + Headers
        Authorization: Token ***********************************

+ Response 200 (application/json)

    [
        {
            "id": 57,
            "title": "pouyanbroker2",
            "version": "1.0.0",
            "image": null,
            "samples": []
        },
        {
            "id": 36,
            "title": "سیب اپ",
            "version": "0.0.0.1",
            "image": null,
            "samples": []
        },
        {
            "id": 8,
            "title": "بیمه سامان",
            "version": "0.0.0.1",
            "image": null,
            "samples": [
                {
                    "text": "خرید بیمه تکمیلی بدون بیمه پایه امکان پذیر است؟"
                },
                {
                    "text": "آيا دستگاه تست قند خون،سوزن و نوار آن پرداخت ميشود؟"
                },
                {
                    "text": "آيا هزينه هاي مربوط به آزمايشات و سونوگرافي هاي دوران بارداري در بيمه نامه درمان انفرادي پرداخت مي شود؟"
                },
                {
                    "text": "آیا آستیگمات،دوربینی،نزدیک بینی یا جمع قدر مطلق نقص بینایی هر چشم تحت پوشش است؟"
                }
            ]
        }
    ]


## چت‌های یک فضای کاری [/workspaces/{workspace_id}/chats]

هر چت یک جلسه گفتگو بین کاربر و چت‌بات است. یک فضای کاری می‌تواند چندین جلسه چت داشته باشد. چت‌های هر روز در تاریخ همان روز دسته‌بندی می‌شوند.

+ Parameters

    + workspace_id: `1` (number) - شناسه فضای کاری

### لیست همه چت‌ها [GET]

+ Request (application/json)

    + Headers
        Authorization: Token ***********************************

+ Response 200 (application/json)

    [
        {
            "date": "2024-09-14",
            "chats": [
                {
                    "id": 3650,
                    "title": "چه کاری انجام میدهی"
                },
                {
                    "id": 3649,
                    "title": "سلام"
                }
            ]
        },
        {
            "date": "2024-09-07",
            "chats":[
                {
                    "id": 3524,
                    "title": "کدام بانک ها ارز اربعین می‌دهند؟"
                }
            ]
        }
    ]

### ساخت یک چت جدید [POST]

+ Request (application/json)

    + Headers
        Authorization: Token ***********************************

    + ‌Body

        {
            "text":"کدام بانک ها ارز اربعین می‌دهند؟"
        }

+ Response 200 (application/json)

    {
        "chat_id": 4153,
        "reply": " با مراجعه به شعب منتخب 7 بانک ملی، تجارت، صادرات، ملت، پست بانک، پارسیان و سپه، می‌توانید ارز اربعین را دریافت کنید.",
        "message_id": 29292,
        "suggestions": [
            "ارز اربعین چقدر است و از کدام بانک‌ها می‌توان تهیه کرد؟",
            "چقدر ارز اربعین می‌دهند؟"
        ]
    }

### حذف همه چت‌ها [DELETE]

+ Response 200 (No Content)

## پیام‌های یک چت [/chats/{chat_id}/messages]
هر چت می‌تواند شامل چندین پیام باشد که بین کاربر و چت‌بات مبادله می‌شود. هر یک از این پیام‌ها شناسه و جزئیات خاص خود را دارد.

+ Parameters
    + chat_id: 1 (number) - شناسه چت

### لیست همه پیام‌ها [GET]

+ Request (application/json)

    + Headers
        Authorization: Token ***********************************

+ Response 200 (application/json)

    [
        {
            "id": 27073,
            "content": "لینک خرید ارز اربعین در روبیکا چیست؟",
            "audio": null,
            "message_answer": "برای خرید ارز اربعین از طریق اپلیکیشن روبیکا، می‌توانید به لینک زیر مراجعه کنید:\n\nhttps://go.rubika.ir/arbaeen1",
            "like": null,
            "created": "2024-09-07T07:48:53.094209Z"
        },
        {
            "id": 27072,
            "content": "کدام بانک ها ارز اربعین می‌دهند؟",
            "audio": null,
            "message_answer": " با مراجعه به شعب منتخب 7 بانک ملی، تجارت، صادرات، ملت، پست بانک، پارسیان و سپه، می‌توانید ارز اربعین را دریافت کنید.",
            "like": null,
            "created": "2024-09-07T07:48:47.646516Z"
        }
    ]

### ساخت یک پیام جدید [POST]

+ Request (application/json)

    + Headers
        Authorization: Token ***********************************
    
    + Body

        {
            text: "کدام بانک ها ارز اربعین می‌دهند؟"
        }

+ Response 200 (application/json)

    {
        "message_id": 29293,
        "reply": " با مراجعه به شعب منتخب 7 بانک ملی، تجارت، صادرات، ملت، پست بانک، پارسیان و سپه، می‌توانید ارز اربعین را دریافت کنید.",
        "suggestions": [
            "ارز اربعین چقدر است و از کدام بانک‌ها می‌توان تهیه کرد؟",
            "چقدر ارز اربعین می‌دهند؟"
        ]
    }
