
FORMAT: 1A
HOST: https://replai.roshan-ai.ir

# ریپلای
ریپلای یک دستیار گفتگوی هوشمند است. این ابزار در نقش یک نیروی پشتیبانیِ همیشه آنلاین، پیام‌های ارسالی کاربران را در هر ساعت از شبانه‌روز می‌گیرد و بعد از درک مفهوم پیام، از میان پاسخ‌های از پیش آماده شده، پاسخ مناسبی را برای کاربر ارسال یا تولید می‌کند. در محیط دموی این پروژه کاربر می‌تواند فضای تست اختصاصی خود را داشته باشد، اطلاعات آن را شخصی‌سازی کند و این فضا را از طریق واسط گرافیکی یا API ارزیابی کند.
برای ارزیابی فضا در محیط کاربری گرافیکی بایستی نام کاربر و گذرواژه و برای ارزیابی از طریق API بایستی کلید اتصال به آن را از تیم فروشِ روشن دریافت کنید.

## آشنایی با اصطلاحات
برای کار با ریپلای ابتدا لازم است با اصطلاحات مرتبط با این ابزار آشنا شوید. در این بخش، این اصطلاحات معرفی شده است.

### فضای کار (Workspace)

فضاهای کار، محیط تست نسخه‌های مختلف ابزار ما هستند که به شیوه‌های مختلفی توسعه پیدا کرده‌اند یا داده‌های مختلفی برای پاسخگویی به پرسش‌ها در نظر می‌گیرند.در محیط کاربری گرافیکی به شما دسترسی یک یا چند فضای کار داده شده که قابل مشاهده و تغییر است و در API از طریق واسط مخصوص می‌توانید اطلاعات فضاهای کاری که دسترسی دارید را دریافت کنید.

### گفتگو (Chat)

در هر فضای کاری می‌توانید گفتگوهای مختلفی را شروع کنید و یا هر زمان که بخواهید گفتگوهای قبلی را ادامه دهید. پیام‌های یک گفتگو این امکان را دارند که با هم ارتباط معنایی داشته باشند که این تابع ویژگی‌های فضای کار است و ممکن است در بعضی فضاهای کار این قابلیت وجود نداشته باشد.

### پیام (Message)

پیام‌ها، متن‌های ارسالی از سوی کاربر هستند که ریپلای برای هر کدام از آن‌ها یک پاسخ تولید می‌کند. پاسخ به یک پیام جز مشخصات همان پیام است و برای ذخیرهٔ پاسخ، یک پیام جدید تولید نمی‌شود.

## فهرست فضاهای کار موجود [/api/workspaces]
فهرست فضاهای کاری منتصب به کاربر جاری را برمی‌گرداند..در پاسخ برگشتی، `id`بیانگر شناسهٔ فضای کاری است، `title` عنوان فضای کاری، `version` نسخه فضای کاری، `texts` نمونه پیام‌های ارسالی برای گفتگو و `icon` تصاویر پروفایل فضای کاری است.

### مثال [GET]
+ Request (application/json)
    + Headers       
        Authorization: Token TOKEN_KEY
+ Response 200 (application/json)
            [
                {
                    "id": 22,
                    "title": "p24_api",
                    "version": "1.0.0",
                    "texts": [
                        ""
                    ],
                    "icon": null
                }
            ]

## فهرست گفتگوهای فضای کار [/api/{workspaces_id}/chats]
فهرست گفتگوهای یک فضای کاری مشخص را برمی‌گرداند..در پاسخ برگشتی، `date`بیانگر تاریخ شروع گفتگو است، `chats` لیست گفتگوهای یک تاریخ خاص، `id` شناسه گفتگو و `title` عنوان گفتگو است. مقدار فیلد title به صورت خودکار توسط سامانه تولید می‌شود.

+ Parameters
 	+ workspaces_id: (required, number) - شناسهٔ فضای کاری‌ای که می‌خواهید فهرست گفتگوهای آن دریافت کنید.

### مثال [GET]
+ Request (application/json)
    + Headers       
        Authorization: Token TOKEN_KEY
+ Response 200 (application/json)
            [
                {
                    "date": "2024-01-15",
                    "chats": [
                        {
                            "id": 1557,
                            "title": "آیا گرفتن نوبت در سا"
                        }
                    ]
                },
                {
                    "date": "2024-01-14",
                    "chats": [
                        {
                            "id": 1553,
                            "title": "گرفتن نوبت در سامانه"
                        }
                    ]
                }
            ]

## ایجاد یک گفتگوی جدید [/api/{workspace_id}/chats]
یک گفتگوی جدید در یک فضای کاری مشخص ایجاد می‌کند. در پاسخ برگشتی، `chat_id`بیانگر شناسه گفتگو است، `text` متن پیام آغازین گفتگو، `reply` متن پاسخ به پیام آغازین گفتگو و `message_id` شناسهٔ پیام آغازین گفتگو است.

+ Parameters
 	+ workspaces_id: (required, number) - شناسهٔ فضای کاری‌ای که می‌خواهید یک گفتگوی جدید در آن ایجاد کنید.

### نمونه [POST]
+ Request (application/json)
    + Headers
            Authorization: Token TOKEN_KEY    
    + Attributes
 	 	- text: (string, required) - متن پیام آغازین گفتگو.
    + Body
            {
                "text": "گرفتن نوبت در سامانه پذیرش24 برای من هزینه ای دارد؟"
            }
+ Response 200 (application/json)
            {
                "chat_id": 1559,
                "reply": "سامانه پذیرش24 در قبال فرآیند نوبت هیچگونه هزینه ای دریافت نمی‌کند و اگر بعد از ثبت نوبت به درگاه پرداخت متصل شدید، این درگاه متعلق به پزشک و یا مرکز درمانی مربوطه می‌باشد و پذیرش24 هیچ دخل و تصرفی در این هزینه ها ندارد.\n",
                "message_id": 4760
            }

## فهرست پیام‌های یک گفتگو [/api/chats/{chat_id}/messages]
فهرست پیام‌های موجود در یک گفتگوی مشخص را برمی‌گرداند. در پاسخ برگشتی، `id`بیانگر شناسه پیام است، `text` متن پیام، `reply` متن پاسخ به پیام، `like` نشان‌دهندهٔ پسنیدن پاسخ، `dislike` نشانگر نپسندیدن پاسخ و `created_at` زمان ایجاد پیام است.

+ Parameters
 	+ chat_id: (required, number) - شناسهٔ گفتگویی که می‌خواهید فهرست پیام‌های آن را دریافت کنید.

### نمونه [GET]
+ Request (application/json)
    + Headers
            Authorization: Token TOKEN_KEY    
+ Response 200 (application/json)
        [
            {
                "id": 4702,
                "text": "چه طور نوبت خود را کنسل کنم؟",
                "reply": "شما از طریق قسمت “نوبت‌های من” هم از طریق اپلیکیشن و هم از طریق وبسایت میتونید نوبت ثبت شده خودتون رو لغو کنید.\n",
                "like": 0,
                "dislike": 0,
                "created_at": "2024-01-14T15:11:45.496928Z"
            },
            {
                "id": 4701,
                "text": "گرفتن نوبت در سامانه پذیرش24 برای من هزینه ای دارد؟",
                "reply": "سامانه پذیرش24 در قبال فرآیند نوبت هیچگونه هزینه ای دریافت نمی‌کند و اگر بعد از ثبت نوبت به درگاه پرداخت متصل شدید، این درگاه متعلق به پزشک و یا مرکز درمانی مربوطه می‌باشد و پذیرش24 هیچ دخل و تصرفی در این هزینه ها ندارد.\n",
                "like": 0,
                "dislike": 0,
                "created_at": "2024-01-14T15:10:28.490395Z"
            }
        ]

## ایجاد یک پیام جدید [/api/{chat_id}/messages]
یک پیام جدید در یک گفتگوی مشخص ایجاد می‌کند. در پاسخ برگشتی، `text`بیانگر متن پیام جدید است، `message_id` شناسهٔ پیام جدید و `reply` متن پاسخ به این پیام است.

+ Parameters
 	+ chat_id: (required, number) - شناسهٔ گفتگویی که می‌خواهید یک پیام جدید در آن ایجاد کنید.

### نمونه [POST]
+ Request (application/json)
    + Headers
            Authorization: Token TOKEN_KEY    
    + Attributes
 	 	- text: (string, required) - متن پیام.
    + Body
            {
                "text": "چه طور نوبت خود را کنسل کنم؟"
            }
+ Response 200 (application/json)
            {
                "message_id": 4765,
                "reply": "شما از طریق قسمت “نوبت‌های من” هم از طریق اپلیکیشن و هم از طریق وبسایت میتونید نوبت ثبت شده خودتون رو لغو کنید.\n"
            }