
FORMAT: 1A
HOST: http://targar.ir

# ترگار
ترگار ای پی ای ترجمه است انگلیسی به فارسی و فارسی به انگلیسی است.
## ترجمه متن [/api/translate/]

### مثال [POST]
ورودی این تابع متن مورد نظر جهت ترجمه، زبان مبدا و زبان مقصد است و خروجی آن متن ترجمه شده میباشد.

+ Request (application/json)
    + Headers       
        Authorization: Token TOKEN_KEY    
    + Attributes
        - text:  Text (string, required) - متن جهت ترجمه. 
        - translateFrom: Text (string, required) - زبان مبدا. 
        - translateTo: Text (string, required) - زبان مقصد. 
    + Body
        {
            "text": "سلام",
            "translateFrom": "persian",
            "translateTo": "english"
        }
+ Response 200 (application/json)
    
    {
        "Translation":"Hi.",
    }
    

